name: release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/cbl-mariner/base/core:2.0
    permissions:
      contents: write
    steps:
      - name: Install dependencies
        run: unset HOME; tdnf install -y build-essential git tar rpm-build ca-certificates
      - uses: actions/checkout@v2
      - name: build
        run: make rpm
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            rpmbuild/RPMS/x86_64/*.rpm
